@startuml
class Member{
    e-mail : String
}

class BoardMember{
}

class Event{
    date : Date
    description : String
    assign(l : Location) : void
}

class Conference{
    max_attendees : Integer
}

class BoardMeeting{
}

class Location{
    
}

class Person{
}

class AAUOC{
}

AAUOC o-- Event
AAUOC o-- Person
AAUOC o-- Location
Event -- Location
Event -- Member
Event <|-- Conference
Event <|-- BoardMeeting
Conference -- Person
BoardMeeting -- BoardMember
Person <|-- Member
Member <|-- BoardMember


@enduml