@startuml
class Member{
    e-mail : String
}

class BoardMember{
}

class Event{
    date : Date
    description : String
    assign(l : Location) : void
}

class Conference{
    max_attendees : Integer
}

class BoardMeeting{
}

class Location{
    description : String
    address : String
}

class Person{
    name : String
}

class AAUOC{
    newLocation(l : Location) : void
    newEvent(e : Event) : void
    newPerson(p : Person) : void
    informEvent(e : Event) : void
    register(m : Member,e : Event) : void
}

AAUOC o-- "0..*" Event
AAUOC o-- "0..*" Person
AAUOC o-- "0..*" Location
Event "0..*" -- "   1" Location : isLocated in
Event "0..*" -- "0..*" Member : attendsTo
Event <|-- Conference
Event <|-- BoardMeeting
Conference "0..*" -- "0..*" Person : attendsTo
BoardMeeting "0..*" -- "0..*" BoardMember : attendsTo
Person <|-- Member
Member <|-- BoardMember


@enduml